"""foundation_explicit"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b82b7a1a044f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE TYPE category_status AS ENUM ('queued', 'fetching', 'processing', 'complete', 'unavailable', 'failed')")
    op.execute("CREATE TYPE confidence AS ENUM ('high', 'medium', 'low')")
    op.execute("CREATE TYPE opportunity_confidence AS ENUM ('high', 'medium', 'low')")
    op.execute("CREATE TYPE opportunity_status AS ENUM ('suggested', 'accepted', 'edited', 'rejected')")
    op.execute("CREATE TYPE job_stage AS ENUM ('queued', 'fetching', 'processing', 'derivatives', 'complete', 'failed', 'partial')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('access_method', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('spatial_resolution', sa.String(length=100), nullable=True),
    sa.Column('temporal_resolution', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysis_source_refs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('derived_table', sa.String(length=80), nullable=False),
    sa.Column('derived_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_source_refs_organization_id'), 'analysis_source_refs', ['organization_id'], unique=False)
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('organization_users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('pricebook_items',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_price_low', sa.Float(), nullable=False),
    sa.Column('unit_price_high', sa.Float(), nullable=False),
    sa.Column('is_example_value', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricebook_items_organization_id'), 'pricebook_items', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('client_goals',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_goals_organization_id'), 'client_goals', ['organization_id'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', postgresql.ENUM('queued', 'fetching', 'processing', 'derivatives', 'complete', 'failed', 'partial', name='job_stage', create_type=False), nullable=False),
    sa.Column('category_status', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('supporting_data_refs', sa.JSON(), nullable=False),
    sa.Column('status', postgresql.ENUM('suggested', 'accepted', 'edited', 'rejected', name='opportunity_status', create_type=False), nullable=False),
    sa.Column('confidence', postgresql.ENUM('high', 'medium', 'low', name='opportunity_confidence', create_type=False), nullable=True),
    sa.Column('requires_field_verification', sa.Boolean(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 autogenerate also emits these indexes; raw IF NOT EXISTS avoids duplicate creation.
    op.execute("CREATE INDEX IF NOT EXISTS idx_opportunities_geometry ON opportunities USING gist (geometry)")
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_table('project_features',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_project_features_geometry ON project_features USING gist (geometry)")
    op.create_index(op.f('ix_project_features_organization_id'), 'project_features', ['organization_id'], unique=False)
    op.create_table('properties',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_properties_geometry ON properties USING gist (geometry)")
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_table('proposals',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_organization_id'), 'proposals', ['organization_id'], unique=False)
    op.create_table('scope_items',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pricebook_item_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_price_low', sa.Float(), nullable=False),
    sa.Column('unit_price_high', sa.Float(), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=True),
    sa.Column('estimated_total_low', sa.Float(), nullable=False),
    sa.Column('estimated_total_high', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pricebook_item_id'], ['pricebook_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_scope_items_geometry ON scope_items USING gist (geometry)")
    op.create_index(op.f('ix_scope_items_organization_id'), 'scope_items', ['organization_id'], unique=False)
    op.create_table('parcels',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('appraisal_parcel_id', sa.String(length=150), nullable=False),
    sa.Column('situs_address', sa.String(length=500), nullable=True),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('appraisal_record_acres', sa.Float(), nullable=True),
    sa.Column('computed_acres', sa.Float(), nullable=True),
    sa.Column('raw_source_attributes', sa.JSON(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_parcels_geometry ON parcels USING gist (geometry)")
    op.create_index(op.f('ix_parcels_organization_id'), 'parcels', ['organization_id'], unique=False)
    op.create_table('proposal_sections',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_sections_organization_id'), 'proposal_sections', ['organization_id'], unique=False)
    op.create_table('site_analyses',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_analyses_organization_id'), 'site_analyses', ['organization_id'], unique=False)
    op.create_table('analysis_categories',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'fetching', 'processing', 'complete', 'unavailable', 'failed', name='category_status', create_type=False), nullable=False),
    sa.Column('confidence', postgresql.ENUM('high', 'medium', 'low', name='confidence', create_type=False), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_categories_organization_id'), 'analysis_categories', ['organization_id'], unique=False)
    op.create_table('analysis_layers',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('object_store_key', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_analysis_layers_geometry ON analysis_layers USING gist (geometry)")
    op.create_index(op.f('ix_analysis_layers_organization_id'), 'analysis_layers', ['organization_id'], unique=False)
    op.create_table('derived_metrics',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derived_metrics_organization_id'), 'derived_metrics', ['organization_id'], unique=False)
    op.create_table('ecological_units',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('system_vegetation_type', sa.String(length=255), nullable=True),
    sa.Column('source_classification_code', sa.String(length=100), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('parcel_percent', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_ecological_units_geometry ON ecological_units USING gist (geometry)")
    op.create_index(op.f('ix_ecological_units_organization_id'), 'ecological_units', ['organization_id'], unique=False)
    op.create_table('flood_zones',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('zone_classification', sa.String(length=100), nullable=True),
    sa.Column('source_discriminator', sa.String(length=40), nullable=False),
    sa.Column('acres_intersected', sa.Float(), nullable=True),
    sa.Column('parcel_percent', sa.Float(), nullable=True),
    sa.Column('annual_chance', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_flood_zones_geometry ON flood_zones USING gist (geometry)")
    op.create_index(op.f('ix_flood_zones_organization_id'), 'flood_zones', ['organization_id'], unique=False)
    op.create_table('soil_units',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('mukey', sa.String(length=50), nullable=False),
    sa.Column('musym', sa.String(length=50), nullable=True),
    sa.Column('map_unit_name', sa.String(length=255), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('parcel_percent', sa.Float(), nullable=True),
    sa.Column('dominant_component_name', sa.String(length=255), nullable=True),
    sa.Column('component_percent', sa.Float(), nullable=True),
    sa.Column('slope_low', sa.Float(), nullable=True),
    sa.Column('slope_representative', sa.Float(), nullable=True),
    sa.Column('slope_high', sa.Float(), nullable=True),
    sa.Column('drainage_class', sa.String(length=100), nullable=True),
    sa.Column('hydrologic_group', sa.String(length=20), nullable=True),
    sa.Column('available_water_storage', sa.Float(), nullable=True),
    sa.Column('ksat', sa.Float(), nullable=True),
    sa.Column('depth_to_restrictive_layer', sa.Float(), nullable=True),
    sa.Column('flooding_frequency', sa.String(length=100), nullable=True),
    sa.Column('ponding_class', sa.String(length=100), nullable=True),
    sa.Column('farmland_classification', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_soil_units_geometry ON soil_units USING gist (geometry)")
    op.create_index(op.f('ix_soil_units_organization_id'), 'soil_units', ['organization_id'], unique=False)
    op.create_table('wells',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('state_well_number', sa.String(length=100), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('aquifer', sa.String(length=150), nullable=True),
    sa.Column('use_type', sa.String(length=100), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('distance_to_parcel', sa.Float(), nullable=True),
    sa.Column('query_radius_miles', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_wells_geometry ON wells USING gist (geometry)")
    op.create_index(op.f('ix_wells_organization_id'), 'wells', ['organization_id'], unique=False)
    op.create_table('wetlands',
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('nwi_attribute_code', sa.String(length=100), nullable=True),
    sa.Column('wetland_type', sa.String(length=255), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('intersects_parcel', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['site_analyses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_wetlands_geometry ON wetlands USING gist (geometry)")
    op.create_index(op.f('ix_wetlands_organization_id'), 'wetlands', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wetlands_organization_id'), table_name='wetlands')
    op.drop_index('idx_wetlands_geometry', table_name='wetlands', postgresql_using='gist')
    op.drop_table('wetlands')
    op.drop_index(op.f('ix_wells_organization_id'), table_name='wells')
    op.drop_index('idx_wells_geometry', table_name='wells', postgresql_using='gist')
    op.drop_table('wells')
    op.drop_index(op.f('ix_soil_units_organization_id'), table_name='soil_units')
    op.drop_index('idx_soil_units_geometry', table_name='soil_units', postgresql_using='gist')
    op.drop_table('soil_units')
    op.drop_index(op.f('ix_flood_zones_organization_id'), table_name='flood_zones')
    op.drop_index('idx_flood_zones_geometry', table_name='flood_zones', postgresql_using='gist')
    op.drop_table('flood_zones')
    op.drop_index(op.f('ix_ecological_units_organization_id'), table_name='ecological_units')
    op.drop_index('idx_ecological_units_geometry', table_name='ecological_units', postgresql_using='gist')
    op.drop_table('ecological_units')
    op.drop_index(op.f('ix_derived_metrics_organization_id'), table_name='derived_metrics')
    op.drop_table('derived_metrics')
    op.drop_index(op.f('ix_analysis_layers_organization_id'), table_name='analysis_layers')
    op.drop_index('idx_analysis_layers_geometry', table_name='analysis_layers', postgresql_using='gist')
    op.drop_table('analysis_layers')
    op.drop_index(op.f('ix_analysis_categories_organization_id'), table_name='analysis_categories')
    op.drop_table('analysis_categories')
    op.drop_index(op.f('ix_site_analyses_organization_id'), table_name='site_analyses')
    op.drop_table('site_analyses')
    op.drop_index(op.f('ix_proposal_sections_organization_id'), table_name='proposal_sections')
    op.drop_table('proposal_sections')
    op.drop_index(op.f('ix_parcels_organization_id'), table_name='parcels')
    op.drop_index('idx_parcels_geometry', table_name='parcels', postgresql_using='gist')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_scope_items_organization_id'), table_name='scope_items')
    op.drop_index('idx_scope_items_geometry', table_name='scope_items', postgresql_using='gist')
    op.drop_table('scope_items')
    op.drop_index(op.f('ix_proposals_organization_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_index('idx_properties_geometry', table_name='properties', postgresql_using='gist')
    op.drop_table('properties')
    op.drop_index(op.f('ix_project_features_organization_id'), table_name='project_features')
    op.drop_index('idx_project_features_geometry', table_name='project_features', postgresql_using='gist')
    op.drop_table('project_features')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index('idx_opportunities_geometry', table_name='opportunities', postgresql_using='gist')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_client_goals_organization_id'), table_name='client_goals')
    op.drop_table('client_goals')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pricebook_items_organization_id'), table_name='pricebook_items')
    op.drop_table('pricebook_items')
    op.drop_table('organization_users')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_analysis_source_refs_organization_id'), table_name='analysis_source_refs')
    op.drop_table('analysis_source_refs')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('data_sources')
    op.execute("DROP TYPE category_status")
    op.execute("DROP TYPE confidence")
    op.execute("DROP TYPE opportunity_confidence")
    op.execute("DROP TYPE opportunity_status")
    op.execute("DROP TYPE job_stage")
    # ### end Alembic commands ###
